force-app/main/default/objects/Public_Event__c/Public_Event__c.object-meta.xml
<CustomObject>
    <label>Public Event</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Public Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Event__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/fields/Main_Venue__c.field-meta.xml
<CustomField>
    <fullName>Main_Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Public Events</relationshipLabel>
    <relationshipName>Public_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PublicEvent_Test.cls
/*
@Author:-Tuğrul GÜL
@Description:- This code is created for Public Event Tests
@Created:- 27/05/2022
@Last Updated:- 27/05/2022
*/
@isTest
public class PublicEvent_Test{

    /* 
    @param:- None
    @description:- Inserts Public Events and Venues
    @returns:- None
    */
    @isTest
    static void testPublicEventwithVenues() {
        Venue__c[] vList = TestDataFactory.createVenues(1);
        Public_Event__c[] pList = TestDataFactory.createPublicEvents(5,vList);

        List<Public_Event__c> peList = [SELECT Id, City__c, Country__c, Main_Venue__r.City__c, Main_Venue__r.Country__c FROM Public_Event__c];
        for(Integer i = 0; i<5; i++ ){
            if(math.mod(i, 2) == 0){
                System.assertEquals(peList[i].Main_Venue__r.City__c, peList[i].City__c, 'City field was not updated from Main Venue' );
                System.assertEquals(peList[i].Main_Venue__r.Country__c, peList[i].Country__c, 'Country field was not updated fromm Main Venue' );
            }else{
                System.assertEquals(peList[i].Main_Venue__r.City__c, peList[i].City__c, 'City field was not set for Public Event' );
                System.assertEquals(peList[i].Main_Venue__r.Country__c, peList[i].Country__c, 'Country field was not set for Public Event' );
            }
        }
    }
}    