force-app/main/default/objects/Public_Event__c/Public_Event__c.object-meta.xml
<CustomObject>
    <label>Public Event</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Public Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Event__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/fields/Main_Venue__c.field-meta.xml
<CustomField>
    <fullName>Main_Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Public Events</relationshipLabel>
    <relationshipName>Public_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dreamforce</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>World Tour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Room_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Room_Capacity__c</fullName>
    <label>Room Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Is_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this session mandatory for the event</description>
    <label>Is Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Public_Event__c.field-meta.xml
<CustomField>
    <fullName>Public_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Public Event</label>
    <referenceTo>Public_Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Room</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Room__c.In_Maintenance__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Room_Capacity__c</fullName>
    <label>Room Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Venue_and_Room_Test_Class.cls
// After_Insert_Update_Event_Registration flow test class
@isTest

public class Venue_and_Room_Test_Class {

    //Test Create Venues
    @isTest
        static void testVenue() {

        //Create Venues with all required fields
        List<Venue__c> vList = new List<Venue__c>();
        for(Integer i = 0; i<5; i++){
            Venue__c ve = new Venue__c( Name = 'Venue Test'+ String.valueOf(i),
                                        Street__c = 'Alsancak',
                                        City__c = 'İzmir',
                                        Country__c = 'Turkey'
        );
        vList.add(ve);
        }
        insert vList;

        List<Venue__c> veList = [SELECT Name, ID FROM Venue__c];
        System.debug('Venues ==>>' + veList);
    }

    //Test Create Rooms for Venue
    @isTest
        static void testRoom() {

        //Create Venues with all required fields
        List<Venue__c> vList = new List<Venue__c>();
        for(Integer i = 0; i<5; i++){
            Venue__c ve = new Venue__c( Name = 'Venue Test'+ String.valueOf(i),
                                        Street__c = 'Alsancak',
                                        City__c = 'İzmir',
                                        Country__c = 'Turkey'
        );
        vList.add(ve);
        }
        insert vList;
        
        //Create Rooms with all required fields
        List<Room__c> rList = new List<Room__c>();
        for(Integer i = 0; i<3; i++){
            Room__c ro = new Room__c(   Name = 'Room Test' + String.valueOf(i),
                                        Room_Capacity__c = 25 + i*25,
                                        Venue__c = vList[0].Id
        );
        rList.add(ro);
        }
        
        for(Integer i = 0; i<2; i++){
            Room__c ro = new Room__c(   Name = 'Room Test' + String.valueOf(i),
                                        Room_Capacity__c = 25 + i*25,
                                        Venue__c = vList[1].Id
        );
        rList.add(ro);
        }
        insert rList;
        
        List<Room__c> reList = [SELECT Name, Id, Venue__c FROM Room__c];
        System.debug('Rooms with Venue information ==>>' + reList);
    }

    //Test Create Sessions with Room Record
    @isTest
        static void testSessionwithRoom() {
        
        //Create Venues with all required fields
        List<Venue__c> vList = new List<Venue__c>();
        for(Integer i = 0; i<5; i++){
            Venue__c ve = new Venue__c( Name = 'Venue Test'+ String.valueOf(i),
                                        Street__c = 'Alsancak',
                                        City__c = 'İzmir',
                                        Country__c = 'Turkey'
            );
        vList.add(ve);
        }
        insert vList;
        
        //Create Rooms with all required fields
        List<Room__c> rList = new List<Room__c>();
        for(Integer i = 0; i<3; i++){
            Room__c ro = new Room__c(   Name = 'Room Test' + String.valueOf(i),
                                        Room_Capacity__c = 25 + i*25,
                                        Venue__c = vList[0].Id
        );
        rList.add(ro);
        }
        insert rList;
        
        //Create Public Event with all required fields
        List<Public_Event__c> pList = new List<Public_Event__c>();
        for(Integer i =0; i<5;i++){
            Public_Event__c pe = new Public_Event__c( Name = 'Public Event Test' + String.valueOf(i),
                                                    Type__c = 'Dreamforce',
                                                    Start_Date__c = Datetime.now(),
                                                    End_Date__c = (Datetime.now()).addMonths(1),
                                                    City__c = 'İzmir',
                                                    Country__c = 'Turkey',
                                                    Main_Venue__c = vList[0].Id
        );
        pList.add(pe);
        }
        insert pList;

        //Create Sessions with all required fields
        List<Session__c> sList = new List<Session__c>();
        for(Integer i = 0; i<3; i++){
            Session__c  s = new Session__c( Name = 'Session Test' + String.valueOf(i),
                                            Public_Event__c = pList[0].Id,
                                            Start_Date_Time__c = (Datetime.now()).addDays(i),
                                            End_Date_Time__c = (Datetime.now()).addDays(i+2),
                                            Room__c = rList[i].Id
            );
            if(math.mod(i, 2) == 0){
                s.Is_Mandatory__c = true;
            }else{
                s.Is_Mandatory__c = false;
            }
            sList.add(s);
        }
        insert sList;

        List<Session__c> seList = [SELECT Name, Id, Room__c FROM Session__c];
        System.debug('Sessions with room information' + seList);
    }
}