force-app/main/default/objects/Public_Event__c/Public_Event__c.object-meta.xml
<CustomObject>
    <label>Public Event</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Public Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Event__c/fields/Main_Venue__c.field-meta.xml
<CustomField>
    <fullName>Main_Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Public Events</relationshipLabel>
    <relationshipName>Public_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Room_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Room_Capacity__c</fullName>
    <label>Room Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Public_Event__c.field-meta.xml
<CustomField>
    <fullName>Public_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Public Event</label>
    <referenceTo>Public_Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Room</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Room__c.In_Maintenance__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Room_Capacity__c</fullName>
    <label>Room Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Session_Test.cls
/*
@Author:-Tuğrul GÜL
@Description:- This code is created for Sessions Tests
@Created:- 30/05/2022
@Last Updated:- 30/05/2022
*/
@isTest
public class Session_Test{


    /* 
    @param:- None
    @description:- Create test data
    @returns:- None
    */
    @TestSetup
    static void makeData() {
        Venue__c[] vList = TestDataFactory.createVenues(2);
        Public_Event__c[] pList = TestDataFactory.createPublicEvents(2,vList);
        
        //Create Event Registration with all required fields
        List<Room__c> rList = new List<Room__c>();
        for(Integer i =0; i<5;i++){
            Room__c ro = new Room__c(   Name = 'Test Room ' + string.valueof(i),
                                        Venue__c = vList[1].Id,
                                        Room_Capacity__c = 50 +i*25  
        );
        rList.add(ro);
        }
        insert rList;
    }


    /* 
    @param:- None
    @description:- Create test Sessions 
    @returns:- None
    */
    @isTest
    static void testSessions() {
        List<Venue__c> vList =[SELECT Id FROM Venue__c];
        List<Room__c> rList = [SELECT Id FROM Room__c];
        List<Public_Event__c> pList =[SELECT Id, Main_Venue__c FROM Public_Event__c];
        for(Public_Event__c pe : pList){
            pe.Main_Venue__c = vList[0].Id;
        }
        update pList;
        try {
            System.debug('Room Lists ' + rList);
            Session__c[] sList = TestDataFactory.createMandatorySessions(2,pList, rList);
        }catch (Exception e) {
            system.debug(e.getStackTraceString());
            system.debug('Error' + e.getMessage());
            System.assertEquals(true,e.getMessage().contains('Mandatory sessions can be served only in main venue rooms'));
        }
    }      
}