force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Public_Event__c.field-meta.xml
<CustomField>
    <fullName>Public_Event__c</fullName>
    <label>Public Event</label>
    <referenceTo>Public_Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/Public_Event__c.object-meta.xml
<CustomObject>
    <label>Public Event</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Public Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EventRegistrationDuplicate.cls
public class EventRegistrationDuplicate{
    
    public static void dupEventRegistrationError(List<Event_Registration__c>newTrigEventReg){
    
    List<Event_Registration__c> AllEventReg = [SELECT Public_Event__c, contact__c FROM Event_Registration__c];
    
    Set<Id> AllPublicEvents = new Set<Id>();
    Set<Id> AllConRegisterto = new Set<Id>();
    
    for(Event_Registration__c OneEventReg : AllEventReg){
        
        allPublicEvents.add(OneEventReg.Public_Event__c);
        allConRegisterto.add(OneEventReg.contact__c);
    
    }
    
    for(Event_Registration__c OneEventRegTrig : newTrigEventReg){
    
        if(allPublicEvents.contains(OneEventRegTrig.Public_Event__c)
           && allConRegisterto.contains(OneEventRegTrig.contact__c)){
           
           OneEventRegTrig.addError('This event already registered.');
           }
    }
    }
}