force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Room_Test.cls
/*
@Author:-Tuğrul GÜL
@Description:- This code is created for Rooms Tests
@Created:- 01/06/2022
@Last Updated:- 01/06/2022
*/
@isTest
public class Room_Test{

    /* 
    @param:- None
    @description:- Create test data
    @returns:- None
    */
    @TestSetup
    static void makeData() {
        Venue__c[] vList = TestDataFactory.createVenues(2);
    }

    /* 
    @param:- None
    @description:- Create test Rooms 
    @returns:- None
    */
    @isTest
    static void testRooms() {
        List<Venue__c> vList =[SELECT Id FROM Venue__c];
        Room__c[] rList = TestDataFactory.createRooms(2, vList);

        List<Room__c> roList = [SELECT Id FROM Room__c];
        System.assertEquals(true, roList.size()>0);
    }      
}