force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Attendee.recordType-meta.xml
<RecordType>
    <fullName>Attendee</fullName>
    <active>true</active>
    <label>Attendee</label>
</RecordType>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Event&apos;s cancellation is checked</description>
    <inlineHelpText>If you want to cancel the event registration, tick the checkbox.</inlineHelpText>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <formula>CASE(Contact__r.Contact_Type__c, &quot;Customer&quot;, &quot;Customer&quot;, &quot;Partner&quot;, &quot;Partner&quot;, &quot;Employee&quot;, &quot;Employee&quot;, &quot;Customer&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Public_Event__c.field-meta.xml
<CustomField>
    <fullName>Public_Event__c</fullName>
    <label>Public Event</label>
    <referenceTo>Public_Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/Public_Event__c.object-meta.xml
<CustomObject>
    <label>Public Event</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Public Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Event__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/fields/Main_Venue__c.field-meta.xml
<CustomField>
    <fullName>Main_Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Public Events</relationshipLabel>
    <relationshipName>Public_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dreamforce</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>World Tour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Room_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Room_Capacity__c</fullName>
    <label>Room Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Is_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this session mandatory for the event</description>
    <label>Is Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Public_Event__c.field-meta.xml
<CustomField>
    <fullName>Public_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Public Event</label>
    <referenceTo>Public_Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Room</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Room__c.In_Maintenance__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Room_Capacity__c</fullName>
    <label>Room Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/Session_Registration__c.object-meta.xml
<CustomObject>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Session Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Registration__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact type should be an attendee</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Attendee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Registrations</relationshipLabel>
    <relationshipName>Session_Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Session&apos;s cancellation is checked</description>
    <inlineHelpText>If you want to cancel the session registration, tick the checkbox.</inlineHelpText>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipLabel>Session Registrations</relationshipLabel>
    <relationshipName>Session_Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Registrations</relationshipLabel>
    <relationshipName>Session_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EventRegFlowTest.cls
// After_Insert_Update_Event_Registration flow test class
@isTest
public class EventRegFlowTest {

    //Create test data
    @TestSetup
    static void makeData() {

        //Create a Contact with all required fields    
        Contact cont = new Contact( FirstName = 'Test',
                                    LastName = 'Attendee',
                                    Contact_Type__c = 'Customer' 
                                );
        insert cont;

        //Create Venues with all required fields
        List<Venue__c> vList = new List<Venue__c>();
        for(Integer i = 0; i<5; i++){
            Venue__c ve = new Venue__c( Name = 'Venue Test'+ String.valueOf(i),
                                        Street__c = 'Alsancak',
                                        City__c = 'İzmir',
                                        Country__c = 'Turkey'
            );
        vList.add(ve);
        }
        insert vList;

        //Create Rooms with all required fields
        List<Room__c> rList = new List<Room__c>();
        for(Integer i = 0; i<3; i++){
            Room__c ro = new Room__c(   Name = 'Room Test' + String.valueOf(i),
                                        Room_Capacity__c = 25 + i*25,
                                        Venue__c = vList[0].Id
        );
        rList.add(ro);
        }

        for(Integer i = 0; i<2; i++){
            Room__c ro = new Room__c(   Name = 'Room Test' + String.valueOf(i),
                                        Room_Capacity__c = 25 + i*25,
                                        Venue__c = vList[1].Id
        );
        rList.add(ro);
        }
        
        insert rList;

        //Create Public Event with all required fields
        List<Public_Event__c> pList = new List<Public_Event__c>();
        for(Integer i =0; i<5;i++){
            Public_Event__c pe = new Public_Event__c( Name = 'Public Event Test' + String.valueOf(i),
                                                    Type__c = 'Dreamforce',
                                                    Start_Date__c = Datetime.now(),
                                                    End_Date__c = (Datetime.now()).addMonths(1),
                                                    City__c = 'İzmir',
                                                    Country__c = 'Turkey',
                                                    Main_Venue__c = vList[0].Id
        );
        pList.add(pe);
        }
        insert pList;

        //Create Sessions with all required fields
        List<Session__c> sList = new List<Session__c>();
        for(Integer i = 0; i<3; i++){
            Session__c  s = new Session__c( Name = 'Session Test' + String.valueOf(i),
                                            Public_Event__c = pList[0].Id,
                                            Start_Date_Time__c = (Datetime.now()).addDays(i),
                                            End_Date_Time__c = (Datetime.now()).addDays(i+2),
                                            Room__c = rList[i].Id
            );
            if(math.mod(i, 2) == 0){
                s.Is_Mandatory__c = true;
            }else{
                s.Is_Mandatory__c = false;
            }
            sList.add(s);
        }
        insert sList;
    }

    //Test Flow without Contact Email Information
    @isTest
        static void testWithoutEmail() {
    
        //Get Contact and Public Event
        Contact cont = [SELECT Id FROM Contact WHERE FirstName = 'Test' ];
        List<Public_Event__c> pList = [SELECT Id FROM Public_Event__c];  

        //Create Event Registration with all required fields
        List<Event_Registration__c> evList = new List<Event_Registration__c>();
        for(Integer i =0; i<5;i++){
            Event_Registration__c er = new Event_Registration__c(   Contact__c = cont.Id,
                                                                    Public_Event__c = pList[i].Id
        );
        evList.add(er);
        }
        insert evList;
    }

    //Test Flow with Contact Email Information
    @isTest
        static void testWithEmail() {
    
        //Get Public Event
        List<Public_Event__c> pList = [SELECT Id FROM Public_Event__c]; 
        
        //Create a Contact with all required fields    
        Contact cont = new Contact( FirstName = 'Test',
                                    LastName = 'Attendee',
                                    Contact_Type__c = 'Customer',
                                    Email = 'tgrgl@hotmail.com'   
                                );
        insert cont;
        
        //Create Event Registration with all required fields
        List<Event_Registration__c> evList = new List<Event_Registration__c>();
        for(Integer i =0; i<5;i++){
            Event_Registration__c er = new Event_Registration__c(   Contact__c = cont.Id,
                                                                    Public_Event__c = pList[i].Id
        );
        evList.add(er);
        }
        insert evList;
    
        system.debug('Event Registrations' + evList);

        //Get Session Registrations
        List<Session_Registration__c> sReg =[SELECT Id, Name, Attendee__c FROM Session_Registration__c];
        system.debug('sReg ==>> ' + sReg);
        
        for (Session_Registration__c ss : sReg){
            system.assertEquals(ss.Attendee__c, cont.Id, 'Events reg and Session regs Contacts are different');
        }
    }

    //Test Flow Update without Contact Email Information
    @isTest
        static void testUpdate() {
    
        //Get Contact and Public Event
        Contact cont = [SELECT Id FROM Contact WHERE FirstName = 'Test'];
        List<Public_Event__c> pList = [SELECT Id FROM Public_Event__c];

        //Create Event Registration with all required fields
        List<Event_Registration__c> evList = new List<Event_Registration__c>();
        for(Integer i =0; i<5;i++){
            Event_Registration__c er = new Event_Registration__c(   Contact__c = cont.Id,
                                                                    Public_Event__c = pList[i].Id
        );
        evList.add(er);
        }
        insert evList;

        List<Session_Registration__c> sReg1 =[SELECT Id, Name, Attendee__c, Cancelled__c  FROM Session_Registration__c];
        system.debug('sReg1 ==>> ' + sReg1);

        evList[0].Cancelled__c = true;
        update evList[0];

        List<Session_Registration__c> sReg2 =[SELECT Id, Name, Attendee__c, Cancelled__c  FROM Session_Registration__c];
        system.debug('sReg2 ==>> ' + sReg2);
    }
}