force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Attendee.recordType-meta.xml
<RecordType>
    <fullName>Attendee</fullName>
    <active>true</active>
    <label>Attendee</label>
</RecordType>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <formula>CASE(Contact__r.Contact_Type__c, &quot;Customer&quot;, &quot;Customer&quot;, &quot;Partner&quot;, &quot;Partner&quot;, &quot;Employee&quot;, &quot;Employee&quot;, &quot;Customer&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Public_Event__c.field-meta.xml
<CustomField>
    <fullName>Public_Event__c</fullName>
    <label>Public Event</label>
    <referenceTo>Public_Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/Public_Event__c.object-meta.xml
<CustomObject>
    <label>Public Event</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Public Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Public_Event__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/fields/Main_Venue__c.field-meta.xml
<CustomField>
    <fullName>Main_Venue__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Main Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Public Events</relationshipLabel>
    <relationshipName>Public_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dreamforce</fullName>
            </value>
            <value>
                <fullName>Connections</fullName>
            </value>
            <value>
                <fullName>World Tour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Number_of_Column_Seats__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Column_Seats__c</fullName>
    <label>Number of Column Seats</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Number_of_Row_Seats__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Row_Seats__c</fullName>
    <label>Number of Row Seats</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Is_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this session mandatory for the event</description>
    <label>Is Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Public_Event__c.field-meta.xml
<CustomField>
    <fullName>Public_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Public Event</label>
    <referenceTo>Public_Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Room</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Room__c.In_Maintenance__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
/*
@Author:-Tuğrul GÜL
@Description:- This code is created for Test Setup Data
@Created:- 27/05/2022
@Last Updated:- 01/06/2022
*/
@isTest
public class TestDataFactory {
    
    /*
    @param:- Integer numC
    @description:- Creates as many Contacts as numC value
    @returns:- List<Contact> cList
    */
    public static List<Contact> createContacts(Integer numC) {
        List<Contact> cList = new List<Contact>();
        for(Integer i=0; i<numC; i++){
            Contact c = new Contact(   FirstName = 'Test',
                                        LastName = 'Attendee',
                                        Contact_Type__c = 'Customer'
                                    );
            cList.add(c);
        }
        insert cList;
        return cList;
    }

    /*
    @param:- Integer numP , List<Venue__c> vList
    @description:- Creates as many Public Events as numP value
    @returns:- List<Public_Event__c> pList
    */
    public static List<Public_Event__c> createPublicEvents(Integer numP, List<Venue__c> vList) {
        List<Public_Event__c> pList = new List<Public_Event__c>();
        for(Integer i =0; i<numP;i++){
            Public_Event__c pe = new Public_Event__c(   Name = 'Public Event Test ' + String.valueOf(i),
                                                        Type__c = 'Dreamforce',
                                                        Start_Date__c = Datetime.now(),
                                                        End_Date__c = (Datetime.now()).addMonths(1),
                                                        City__c = 'London',
                                                        Country__c = 'England',
                                                        Main_Venue__c = vList[i].Id
                                                    );
            if(math.mod(i, 2) == 0){
                pe.City__c = null;
                pe.Country__c = null;
            }else{
                pe.City__c = 'İzmir';
                pe.Country__c = 'Türkiye';
            }
            pList.add(pe);
        }
        insert pList;
        return pList;
    }

    /*
    @param:- Integer numEv,List<Contact> cList, List<Public_Event__c> pList
    @description:- Creates as many Contacts as numEv value
    @returns:- List<Event_Registration__c> EvList
    */
    public static List<Event_Registration__c> createEventRegistrations(Integer numEv,List<Contact> cList, List<Public_Event__c> pList) {
        List<Event_Registration__c> evList = new List<Event_Registration__c>();
        for(Integer i =0; i<numEv;i++){
            Event_Registration__c er = new Event_Registration__c(   Contact__c = cList[0].Id,
                                                                    Public_Event__c = pList[i].Id
                                                                );
            evList.add(er);
        }
        insert evList;
        return evList;
    }
        
    /*
    @param:- Integer numS, List<Public_Event__c> pList, List<Room__c> rList
    @description:- Creates as many Public Events as numP value
    @returns:- List<Session__c> pList
    */
    public static List<Session__c> createMandatorySessions(Integer numS, List<Public_Event__c> pList, List<Room__c> rList) {
        List<Session__c> sList = new List<Session__c>();
        for(Integer i = 0; i<numS; i++){
            Session__c  s = new Session__c( Name = 'Session Test' + String.valueOf(i),
                                            Public_Event__c = pList[i].Id,
                                            Start_Date_Time__c = (Datetime.now()).addDays(i),
                                            End_Date_Time__c = (Datetime.now()).addDays(i+2),
                                            Room__c = rList[i].Id
            );
            s.Is_Mandatory__c = true;
            sList.add(s);
        }
        insert sList;
        return sList;
    }

    /*
    @param:- Integer numS, List<Public_Event__c> pList, List<Room__c> rList
    @description:- Creates as many Public Events as numP value
    @returns:- List<Session__c> pList
    */
    public static List<Session__c> createNormalSessions(Integer numS, List<Public_Event__c> pList, List<Room__c> rList) {
        List<Session__c> sList = new List<Session__c>();
        for(Integer i = 0; i<numS; i++){
            Session__c  s = new Session__c( Name = 'Session Test' + String.valueOf(i),
                                            Public_Event__c = pList[i].Id,
                                            Start_Date_Time__c = (Datetime.now()).addDays(i),
                                            End_Date_Time__c = (Datetime.now()).addDays(i+2),
                                            Room__c = rList[i].Id
            );
            s.Is_Mandatory__c = false;
            sList.add(s);
        }
        insert sList;
        return sList;
    }
    
    /*
    @param:- Integer numV 
    @description:- Creates as many Venues as numV value  
    @returns:- List<Venues__c> vList
    */
    public static List<Venue__c> createVenues(Integer numV) {
        List<Venue__c> vList = new List<Venue__c>();
        for(Integer i = 0; i<numV; i++){
            Venue__c ve = new Venue__c( Name = 'Venue Test '+ String.valueOf(i),
                                        Street__c = 'Alsancak',
                                        City__c = 'İzmir',
                                        Country__c = 'Türkiye'
                                    );
            vList.add(ve);
        }
        insert vList;
        return vList;
    }

    /*
    @param:- Integer numR, List<Venue__c> vList
    @description:- Creates as many Rooms as numP value
    @returns:- List<Room__c> pList
    */
    public static List<Room__c> createRooms(Integer numR, List<Venue__c> vList){
        List<Room__c> rList = new List<Room__c>();
        for(Integer i = 0; i<numR; i++){
            Room__c ro = new Room__c(   Name = 'Room Test ' + String.valueOf(i),
                                        Venue__c = vList[i].Id,
                                        Number_of_Column_Seats__c = 10,
                                        Number_of_Row_Seats__c = 10
        );
        rList.add(ro);
        }
        insert rList;
        return rList;
    }
}