force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Attendee.recordType-meta.xml
<RecordType>
    <fullName>Attendee</fullName>
    <active>true</active>
    <label>Attendee</label>
</RecordType>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Event&apos;s cancellation is checked</description>
    <inlineHelpText>If you want to cancel the event registration, tick the checkbox.</inlineHelpText>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <formula>CASE(Contact__r.Contact_Type__c, &quot;Customer&quot;, &quot;Customer&quot;, &quot;Partner&quot;, &quot;Partner&quot;, &quot;Employee&quot;, &quot;Employee&quot;, &quot;Customer&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Public_Event__c.field-meta.xml
<CustomField>
    <fullName>Public_Event__c</fullName>
    <label>Public Event</label>
    <referenceTo>Public_Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Public_Event__c/Public_Event__c.object-meta.xml
<CustomObject>
    <label>Public Event</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Public Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Public_Event__c.field-meta.xml
<CustomField>
    <fullName>Public_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Public Event</label>
    <referenceTo>Public_Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Room</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Room__c.In_Maintenance__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/Session_Registration__c.object-meta.xml
<CustomObject>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Session Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Registration__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact type should be an attendee</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Attendee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Registrations</relationshipLabel>
    <relationshipName>Session_Registrations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Session&apos;s cancellation is checked</description>
    <inlineHelpText>If you want to cancel the session registration, tick the checkbox.</inlineHelpText>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipLabel>Session Registrations</relationshipLabel>
    <relationshipName>Session_Registrations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Registrations</relationshipLabel>
    <relationshipName>Session_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EventRegistration_Test.cls
/*
@Author:-Tuğrul GÜL
@Description:- This code is created for Event Registrations Tests
@Created:- 30/06/2022
@Last Updated:- 01/06/2022
*/
@isTest
public class EventRegistration_Test {

    /* 
    @param:- None
    @description:- Create test data
    @returns:- None
    */
    @TestSetup
    static void makeData() {
        
        Contact[] cList = TestDataFactory.createContacts(2);
        Venue__c[] vList = TestDataFactory.createVenues(5);
        Room__c[] rList = TestDataFactory.createRooms(2,vList);
        Public_Event__c[] pList = TestDataFactory.createPublicEvents(5,vList);
        Session__c[] snList = TestDataFactory.createNormalSessions(2,pList, rList);
        Session__c[] smList = TestDataFactory.createMandatorySessions(2,pList, rList);
    }

    /* 
    @param:- None
    @description:- Create test Event Registrations
    @returns:- None
    */
    @isTest
    static void testSessions() {
        //Get Contacts and Public Events
        List<Contact> cList = [SELECT Id FROM Contact];
        List<Public_Event__c> pList = [SELECT Id FROM Public_Event__c];  

        //Create Event Registrations with all required fields 
        Event_Registration__c[] evList = TestDataFactory.createEventRegistrations(5, cList, pList);

        List<Event_Registration__c> evRList = [SELECT Id FROM Event_Registration__c];
        System.assertEquals(true, evRList.size()>0);
        }

    /* 
    @param:- None
    @description:- Test After Insert Event Registrations at "After Insert Update Event Registration" Flow without Contact's Email Information 
    @returns:- None
    */
    @isTest
    static void testWithoutEmail() {

        //Get Contacts and Public Events
        List<Contact> cList = [SELECT Id FROM Contact];
        List<Public_Event__c> pList = [SELECT Id FROM Public_Event__c];  

        //Create Event Registrations with all required fields 
        Event_Registration__c[] evList = TestDataFactory.createEventRegistrations(5, cList, pList);
    }

    /* 
    @param:- None
    @description:- Test After Insert Event Registrations at "After Insert Update Event Registration" Flow with Contact's Email Information 
    @returns:- None
    */
    @isTest
    static void testWithEmail() {
    
        //Get Public Events
        List<Public_Event__c> pList = [SELECT Id FROM Public_Event__c]; 
        
        //Create a Contacts with all required fields    
        Contact cont = new Contact(     FirstName = 'Test',
                                        LastName = 'Attendee',
                                        Contact_Type__c = 'Customer',
                                        Email = 'tgrgl@hotmail.com'   
                                    );
        insert cont;
        List<Contact> cList = [SELECT Id FROM Contact WHERE Email = 'tgrgl@hotmail.com'];
        
        //Create Event Registrations with all required fields
        Event_Registration__c[] evList = TestDataFactory.createEventRegistrations(5, cList, pList);
    
        system.debug('Event Registrations' + evList);

        //Get Session Registrations
        List<Session_Registration__c> sReg =[SELECT Id, Name, Attendee__c FROM Session_Registration__c];
        system.debug('sReg ==>> ' + sReg);
        
        for (Session_Registration__c ss : sReg){
            system.assertEquals(ss.Attendee__c, cList[0].Id, 'Events reg and Session regs Contacts are different');
        }
    }

    /* 
    @param:- None
    @description:- Test After Update Event Registrations at "After Insert Update Event Registration" Flow without Contact's Email Information
    @returns:- None
    */
    @isTest
    static void testUpdate() {
    
        //Get Contacts and Public Events
        List<Contact> cList = [SELECT Id FROM Contact];
        List<Public_Event__c> pList = [SELECT Id FROM Public_Event__c];

        //Create Event Registrations with all required fields
        Event_Registration__c[] evList = TestDataFactory.createEventRegistrations(5, cList, pList);

        List<Session_Registration__c> sReg1 =[SELECT Id, Name, Attendee__c, Cancelled__c  FROM Session_Registration__c];
        system.debug('sReg1 ==>> ' + sReg1);

        evList[0].Cancelled__c = true;
        update evList[0];

        List<Session_Registration__c> sReg2 =[SELECT Id, Name, Attendee__c, Cancelled__c  FROM Session_Registration__c];
        system.debug('sReg2 ==>> ' + sReg2);

        system.assertEquals(    string.valueOf(sReg1[0].Id) + string.valueOf(sReg1[0].Attendee__c) + string.valueOf(sReg1[0].Cancelled__c),
                                string.valueOf(sReg2[0].Id) + string.valueOf(sReg2[0].Attendee__c) + string.valueOf(!sReg2[0].Cancelled__c),
                                'After Update Event Registrations at "After Insert Update Event Registration" Flow has a problem');
    }
}